import 'package:flutter/material.dart';
import '../models/category_model.dart';
import '../models/service_model.dart';
import '../models/provider_model.dart';
import '../models/booking_model.dart';
import '../models/review_model.dart';
import '../models/banner_model.dart';
import '../models/user_model.dart';

class DummyData {
  DummyData._();

  // ==================== CATEGORIES (50 Ayurvedic Therapies) ====================
  static final List<CategoryModel> categories = [
    // 1
    CategoryModel(
      id: 'cat_1',
      name: 'Full Body Abhyanga',
      iconData: Icons.spa,
      color: const Color(0xFFE65100),
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    ),
    // 2
    CategoryModel(
      id: 'cat_2',
      name: 'Full Body Dhara',
      iconData: Icons.water_drop,
      color: const Color(0xFF0277BD),
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=400',
    ),
    // 3
    CategoryModel(
      id: 'cat_3',
      name: 'Full Body Swedana',
      iconData: Icons.hot_tub,
      color: const Color(0xFFD84315),
      image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400',
    ),
    // 4
    CategoryModel(
      id: 'cat_4',
      name: 'Patra Pottali Swedana',
      iconData: Icons.eco,
      color: const Color(0xFF2E7D32),
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400',
    ),
    // 5
    CategoryModel(
      id: 'cat_5',
      name: 'Ruksha Pinda Swedana',
      iconData: Icons.scatter_plot,
      color: const Color(0xFF795548),
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    ),
    // 6
    CategoryModel(
      id: 'cat_6',
      name: 'Shashtika Shali Pinda Swedana',
      iconData: Icons.grass,
      color: const Color(0xFFF9A825),
      image: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=400',
    ),
    // 7
    CategoryModel(
      id: 'cat_7',
      name: 'Tila Masha Pinda Swedana',
      iconData: Icons.blur_circular,
      color: const Color(0xFF4E342E),
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    ),
    // 8
    CategoryModel(
      id: 'cat_8',
      name: 'Nadi Swedana',
      iconData: Icons.air,
      color: const Color(0xFFE64A19),
      image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400',
    ),
    // 9
    CategoryModel(
      id: 'cat_9',
      name: 'Mastishkya (Shiro Lepa)',
      iconData: Icons.face,
      color: const Color(0xFF7B1FA2),
      image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400',
    ),
    // 10
    CategoryModel(
      id: 'cat_10',
      name: 'Shirodhara',
      iconData: Icons.format_color_fill,
      color: const Color(0xFF1565C0),
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=400',
    ),
    // 11
    CategoryModel(
      id: 'cat_11',
      name: 'Takradhara',
      iconData: Icons.local_drink,
      color: const Color(0xFFFDD835),
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    ),
    // 12
    CategoryModel(
      id: 'cat_12',
      name: 'Shiro Abhyanga',
      iconData: Icons.self_improvement,
      color: const Color(0xFFFF8F00),
      image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400',
    ),
    // 13
    CategoryModel(
      id: 'cat_13',
      name: 'Shiro Pichu',
      iconData: Icons.pan_tool,
      color: const Color(0xFF00897B),
      image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400',
    ),
    // 14
    CategoryModel(
      id: 'cat_14',
      name: 'Greeva Pichu',
      iconData: Icons.accessibility_new,
      color: const Color(0xFF388E3C),
      image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=400',
    ),
    // 15
    CategoryModel(
      id: 'cat_15',
      name: 'Shiro Pichu Dharana',
      iconData: Icons.memory,
      color: const Color(0xFF303F9F),
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    ),
    // 16
    CategoryModel(
      id: 'cat_16',
      name: 'Kati Pichu',
      iconData: Icons.hotel,
      color: const Color(0xFF1976D2),
      image: 'https://images.unsplash.com/photo-1591343395082-e120087004b4?w=400',
    ),
    // 17
    CategoryModel(
      id: 'cat_17',
      name: 'Janu Pichu',
      iconData: Icons.directions_walk,
      color: const Color(0xFF00796B),
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    ),
    // 18
    CategoryModel(
      id: 'cat_18',
      name: 'Spinal Pichu',
      iconData: Icons.straighten,
      color: const Color(0xFF6A1B9A),
      image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=400',
    ),
    // 19
    CategoryModel(
      id: 'cat_19',
      name: 'Kati Basti',
      iconData: Icons.opacity,
      color: const Color(0xFFF57F17),
      image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=400',
    ),
    // 20
    CategoryModel(
      id: 'cat_20',
      name: 'Greeva Basti',
      iconData: Icons.fitness_center,
      color: const Color(0xFF0D47A1),
      image: 'https://images.unsplash.com/photo-1591343395082-e120087004b4?w=400',
    ),
    // 21
    CategoryModel(
      id: 'cat_21',
      name: 'Spinal Basti',
      iconData: Icons.height,
      color: const Color(0xFF4527A0),
      image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=400',
    ),
    // 22
    CategoryModel(
      id: 'cat_22',
      name: 'Janu Basti',
      iconData: Icons.airline_seat_legroom_extra,
      color: const Color(0xFF00695C),
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    ),
    // 23
    CategoryModel(
      id: 'cat_23',
      name: 'Hridaya Basti',
      iconData: Icons.favorite,
      color: const Color(0xFFC62828),
      image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400',
    ),
    // 24
    CategoryModel(
      id: 'cat_24',
      name: 'Nabhi Basti',
      iconData: Icons.radio_button_checked,
      color: const Color(0xFFEF6C00),
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    ),
    // 25
    CategoryModel(
      id: 'cat_25',
      name: 'Akshi Tarpana',
      iconData: Icons.visibility,
      color: const Color(0xFF0288D1),
      image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400',
    ),
    // 26
    CategoryModel(
      id: 'cat_26',
      name: 'Shiro Basti',
      iconData: Icons.mood,
      color: const Color(0xFF4A148C),
      image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400',
    ),
    // 27
    CategoryModel(
      id: 'cat_27',
      name: 'Vamana Karma',
      iconData: Icons.medical_services,
      color: const Color(0xFFB71C1C),
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400',
    ),
    // 28
    CategoryModel(
      id: 'cat_28',
      name: 'Virechana Karma',
      iconData: Icons.local_hospital,
      color: const Color(0xFF1B5E20),
      image: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=400',
    ),
    // 29
    CategoryModel(
      id: 'cat_29',
      name: 'Basti Karma',
      iconData: Icons.health_and_safety,
      color: const Color(0xFF006064),
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400',
    ),
    // 30
    CategoryModel(
      id: 'cat_30',
      name: 'Nasya Karma',
      iconData: Icons.filter_drama,
      color: const Color(0xFF039BE5),
      image: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=400',
    ),
    // 31
    CategoryModel(
      id: 'cat_31',
      name: 'Marma Chikitsa',
      iconData: Icons.touch_app,
      color: const Color(0xFFBF360C),
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    ),
    // 32
    CategoryModel(
      id: 'cat_32',
      name: 'Dry Cupping Therapy',
      iconData: Icons.adjust,
      color: const Color(0xFF5D4037),
      image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=400',
    ),
    // 33
    CategoryModel(
      id: 'cat_33',
      name: 'Wet Cupping Therapy',
      iconData: Icons.bloodtype,
      color: const Color(0xFF880E4F),
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    ),
    // 34
    CategoryModel(
      id: 'cat_34',
      name: 'Raktamokshana',
      iconData: Icons.healing,
      color: const Color(0xFF1B5E20),
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400',
    ),
    // 35
    CategoryModel(
      id: 'cat_35',
      name: 'Sira Bhedana',
      iconData: Icons.colorize,
      color: const Color(0xFFD32F2F),
      image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=400',
    ),
    // 36
    CategoryModel(
      id: 'cat_36',
      name: 'Fire Cupping Therapy',
      iconData: Icons.local_fire_department,
      color: const Color(0xFFFF6F00),
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    ),
    // 37
    CategoryModel(
      id: 'cat_37',
      name: 'Vidalaka',
      iconData: Icons.face_retouching_natural,
      color: const Color(0xFFEC407A),
      image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400',
    ),
    // 38
    CategoryModel(
      id: 'cat_38',
      name: 'Janu Dhara',
      iconData: Icons.waves,
      color: const Color(0xFF00838F),
      image: 'https://images.unsplash.com/photo-1591343395082-e120087004b4?w=400',
    ),
    // 39
    CategoryModel(
      id: 'cat_39',
      name: 'Kati Dhara',
      iconData: Icons.water,
      color: const Color(0xFF01579B),
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=400',
    ),
    // 40
    CategoryModel(
      id: 'cat_40',
      name: 'Manya Dhara / Greeva Dhara',
      iconData: Icons.shower,
      color: const Color(0xFF283593),
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    ),
    // 41
    CategoryModel(
      id: 'cat_41',
      name: 'Prastara Dhara / Spinal Dhara',
      iconData: Icons.trending_flat,
      color: const Color(0xFF6A1B9A),
      image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=400',
    ),
    // 42
    CategoryModel(
      id: 'cat_42',
      name: 'Hridaya Dhara',
      iconData: Icons.monitor_heart,
      color: const Color(0xFFD50000),
      image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400',
    ),
    // 43
    CategoryModel(
      id: 'cat_43',
      name: 'Niruha Basti',
      iconData: Icons.science,
      color: const Color(0xFF33691E),
      image: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=400',
    ),
    // 44
    CategoryModel(
      id: 'cat_44',
      name: 'Medicinal Oil Basti',
      iconData: Icons.invert_colors,
      color: const Color(0xFFFF6F00),
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400',
    ),
    // 45
    CategoryModel(
      id: 'cat_45',
      name: 'Karna Purana',
      iconData: Icons.hearing,
      color: const Color(0xFF0097A7),
      image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400',
    ),
    // 46
    CategoryModel(
      id: 'cat_46',
      name: 'Dry Needling Therapy',
      iconData: Icons.push_pin,
      color: const Color(0xFF546E7A),
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    ),
    // 47
    CategoryModel(
      id: 'cat_47',
      name: 'Agni Karma',
      iconData: Icons.whatshot,
      color: const Color(0xFFE65100),
      image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400',
    ),
    // 48
    CategoryModel(
      id: 'cat_48',
      name: 'Agni Karma by Needle',
      iconData: Icons.build,
      color: const Color(0xFFF4511E),
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    ),
    // 49
    CategoryModel(
      id: 'cat_49',
      name: 'Agni Patra Swedana',
      iconData: Icons.shield,
      color: const Color(0xFF424242),
      image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400',
    ),
    // 50
    CategoryModel(
      id: 'cat_50',
      name: 'Electric Pen Therapy',
      iconData: Icons.electric_bolt,
      color: const Color(0xFFFBC02D),
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    ),
  ];

  // ==================== SERVICES (50 — one per category) ====================
  static final List<ServiceModel> services = [
    // --- srv_1: Full Body Abhyanga (cat_1) ---
    ServiceModel(
      id: 'srv_1',
      name: 'Full Body Abhyanga (Oil Massage)',
      description: 'Traditional Ayurvedic full body warm oil massage for deep relaxation, improved blood circulation and toxin release.',
      categoryId: 'cat_1',
      price: 1499,
      originalPrice: 1999,
      discount: 25,
      duration: '60 mins',
      rating: 4.9,
      reviewCount: 8456,
      included: ['Warm medicated oil', 'Full body massage', 'Marma point stimulation', 'Post-therapy rest'],
      isBestSeller: true,
      bookingCount: 42000,
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    ),
    // --- srv_2: Full Body Dhara (cat_2) ---
    ServiceModel(
      id: 'srv_2',
      name: 'Full Body Dhara Therapy',
      description: 'Continuous pouring of warm medicated oil over the entire body for deep healing and rejuvenation.',
      categoryId: 'cat_2',
      price: 1799,
      originalPrice: 2499,
      discount: 28,
      duration: '45 mins',
      rating: 4.8,
      reviewCount: 5432,
      included: ['Medicated oil preparation', 'Continuous oil pouring', 'Body massage', 'Rest period'],
      bookingCount: 28000,
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=400',
    ),
    // --- srv_3: Full Body Swedana (cat_3) ---
    ServiceModel(
      id: 'srv_3',
      name: 'Full Body Swedana (Steam Therapy)',
      description: 'Herbal steam therapy to open body channels, relieve muscle stiffness and eliminate toxins.',
      categoryId: 'cat_3',
      price: 999,
      originalPrice: 1299,
      discount: 23,
      duration: '30 mins',
      rating: 4.7,
      reviewCount: 6789,
      included: ['Herbal steam preparation', 'Full body steaming', 'Cool down period', 'Herbal water'],
      isBestSeller: true,
      bookingCount: 35000,
      image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400',
    ),
    // --- srv_4: Patra Pottali Swedana (cat_4) ---
    ServiceModel(
      id: 'srv_4',
      name: 'Patra Pottali Swedana (Leaf Bolus)',
      description: 'Fomentation therapy using fresh herbal leaves tied in boluses, excellent for joint pain and inflammation.',
      categoryId: 'cat_4',
      price: 1599,
      originalPrice: 2199,
      discount: 27,
      duration: '45 mins',
      rating: 4.8,
      reviewCount: 4321,
      included: ['Fresh herbal leaves', 'Medicated oil', 'Bolus preparation', 'Targeted fomentation'],
      bookingCount: 22000,
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400',
    ),
    // --- srv_5: Ruksha Pinda Swedana (cat_5) ---
    ServiceModel(
      id: 'srv_5',
      name: 'Ruksha Pinda Swedana (Dry Bolus)',
      description: 'Dry fomentation using herbal powder boluses for Kapha disorders, obesity and water retention.',
      categoryId: 'cat_5',
      price: 1299,
      originalPrice: 1699,
      discount: 23,
      duration: '40 mins',
      rating: 4.6,
      reviewCount: 2345,
      included: ['Herbal powder preparation', 'Dry bolus fomentation', 'Targeted application', 'Post-therapy rest'],
      bookingCount: 12000,
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    ),
    // --- srv_6: Shashtika Shali Pinda Swedana (cat_6) ---
    ServiceModel(
      id: 'srv_6',
      name: 'Shashtika Shali Pinda Swedana',
      description: 'Nourishing therapy using rice boluses cooked in milk and herbal decoction. Strengthens muscles and nerves.',
      categoryId: 'cat_6',
      price: 1899,
      originalPrice: 2499,
      discount: 24,
      duration: '60 mins',
      rating: 4.9,
      reviewCount: 3456,
      included: ['Special rice preparation', 'Milk & herbal decoction', 'Full body bolus massage', 'Abhyanga'],
      isBestSeller: true,
      bookingCount: 18000,
      image: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=400',
    ),
    // --- srv_7: Tila Masha Pinda Swedana (cat_7) ---
    ServiceModel(
      id: 'srv_7',
      name: 'Tila Masha Pinda Swedana',
      description: 'Fomentation with sesame and black gram boluses for Vata disorders, muscle wasting and nerve weakness.',
      categoryId: 'cat_7',
      price: 1399,
      originalPrice: 1899,
      discount: 26,
      duration: '45 mins',
      rating: 4.7,
      reviewCount: 1876,
      included: ['Sesame & black gram preparation', 'Warm bolus massage', 'Oil application', 'Rest period'],
      bookingCount: 9500,
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    ),
    // --- srv_8: Nadi Swedana (cat_8) ---
    ServiceModel(
      id: 'srv_8',
      name: 'Nadi Swedana (Localized Steam)',
      description: 'Localized herbal steam therapy directed at specific body parts for targeted pain relief.',
      categoryId: 'cat_8',
      price: 799,
      originalPrice: 999,
      discount: 20,
      duration: '25 mins',
      rating: 4.6,
      reviewCount: 5678,
      included: ['Herbal steam preparation', 'Localized application', 'Post-therapy care'],
      bookingCount: 25000,
      image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400',
    ),
    // --- srv_9: Mastishkya / Shiro Lepa (cat_9) ---
    ServiceModel(
      id: 'srv_9',
      name: 'Mastishkya (Shiro Lepa / Head Pack)',
      description: 'Herbal paste application on the head to calm the mind, reduce stress and treat headaches.',
      categoryId: 'cat_9',
      price: 899,
      originalPrice: 1199,
      discount: 25,
      duration: '40 mins',
      rating: 4.7,
      reviewCount: 3210,
      included: ['Herbal paste preparation', 'Scalp application', 'Rest period', 'Gentle wash'],
      bookingCount: 15000,
      image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400',
    ),
    // --- srv_10: Shirodhara (cat_10) ---
    ServiceModel(
      id: 'srv_10',
      name: 'Shirodhara',
      description: 'Continuous pouring of warm medicated oil on the forehead. Deeply relaxing therapy for stress, anxiety and insomnia.',
      categoryId: 'cat_10',
      price: 1299,
      originalPrice: 1799,
      discount: 27,
      duration: '45 mins',
      rating: 4.9,
      reviewCount: 9876,
      included: ['Medicated oil', 'Continuous forehead pouring', 'Head massage', 'Rest period'],
      isBestSeller: true,
      bookingCount: 55000,
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=400',
    ),
    // --- srv_11: Takradhara (cat_11) ---
    ServiceModel(
      id: 'srv_11',
      name: 'Takradhara (Buttermilk Dhara)',
      description: 'Medicated buttermilk poured continuously on the forehead. Excellent for psoriasis, stress and cooling therapy.',
      categoryId: 'cat_11',
      price: 1099,
      originalPrice: 1499,
      discount: 26,
      duration: '40 mins',
      rating: 4.7,
      reviewCount: 2987,
      included: ['Medicated buttermilk', 'Continuous pouring', 'Scalp massage', 'Cool down'],
      bookingCount: 14000,
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    ),
    // --- srv_12: Shiro Abhyanga (cat_12) ---
    ServiceModel(
      id: 'srv_12',
      name: 'Shiro Abhyanga (Head Oil Massage)',
      description: 'Therapeutic head oil massage with medicated oils for hair health, stress relief and mental clarity.',
      categoryId: 'cat_12',
      price: 699,
      originalPrice: 899,
      discount: 22,
      duration: '30 mins',
      rating: 4.8,
      reviewCount: 7654,
      included: ['Warm medicated oil', 'Head & scalp massage', 'Neck massage', 'Pressure points'],
      isBestSeller: true,
      bookingCount: 48000,
      image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400',
    ),
    // --- srv_13: Shiro Pichu (cat_13) ---
    ServiceModel(
      id: 'srv_13',
      name: 'Shiro Pichu (Head Oil Soaking)',
      description: 'Cotton pad soaked in warm medicated oil placed on the crown of the head for migraine, hair fall and scalp disorders.',
      categoryId: 'cat_13',
      price: 799,
      originalPrice: 1099,
      discount: 27,
      duration: '30 mins',
      rating: 4.6,
      reviewCount: 2134,
      included: ['Medicated oil preparation', 'Cotton pad soaking', 'Crown application', 'Rest period'],
      bookingCount: 10000,
      image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400',
    ),
    // --- srv_14: Greeva Pichu (cat_14) ---
    ServiceModel(
      id: 'srv_14',
      name: 'Greeva Pichu (Neck Oil Soaking)',
      description: 'Warm medicated oil-soaked cotton pad placed on the neck for cervical pain, stiffness and spondylosis.',
      categoryId: 'cat_14',
      price: 799,
      originalPrice: 1099,
      discount: 27,
      duration: '30 mins',
      rating: 4.7,
      reviewCount: 2456,
      included: ['Warm medicated oil', 'Cotton pad application', 'Neck area treatment', 'Gentle massage'],
      bookingCount: 11000,
      image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=400',
    ),
    // --- srv_15: Shiro Pichu Dharana (cat_15) ---
    ServiceModel(
      id: 'srv_15',
      name: 'Shiro Pichu Dharana (Extended Head Oil)',
      description: 'Extended oil retention on the head with continuous warm oil replenishment for chronic headaches and insomnia.',
      categoryId: 'cat_15',
      price: 999,
      originalPrice: 1299,
      discount: 23,
      duration: '40 mins',
      rating: 4.7,
      reviewCount: 1876,
      included: ['Medicated oil', 'Extended oil retention', 'Head massage', 'Relaxation period'],
      bookingCount: 8500,
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    ),
    // --- srv_16: Kati Pichu (cat_16) ---
    ServiceModel(
      id: 'srv_16',
      name: 'Kati Pichu (Lower Back Oil Soaking)',
      description: 'Oil-soaked cotton pad retained on the lower back for mild lumbar pain, stiffness and muscle strain.',
      categoryId: 'cat_16',
      price: 799,
      originalPrice: 1099,
      discount: 27,
      duration: '30 mins',
      rating: 4.6,
      reviewCount: 2678,
      included: ['Warm medicated oil', 'Cotton pad on lower back', 'Oil retention', 'Gentle massage'],
      bookingCount: 13000,
      image: 'https://images.unsplash.com/photo-1591343395082-e120087004b4?w=400',
    ),
    // --- srv_17: Janu Pichu (cat_17) ---
    ServiceModel(
      id: 'srv_17',
      name: 'Janu Pichu (Knee Oil Soaking)',
      description: 'Warm oil-soaked pad placed over the knee joint for mild knee pain, early arthritis and joint stiffness.',
      categoryId: 'cat_17',
      price: 699,
      originalPrice: 999,
      discount: 30,
      duration: '25 mins',
      rating: 4.6,
      reviewCount: 2345,
      included: ['Medicated oil', 'Cotton pad on knee', 'Oil retention', 'Knee massage'],
      bookingCount: 11500,
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    ),
    // --- srv_18: Spinal Pichu (cat_18) ---
    ServiceModel(
      id: 'srv_18',
      name: 'Spinal Pichu (Spine Oil Soaking)',
      description: 'Oil-soaked cotton pad along the spine for spinal disorders, disc problems and nerve-related pain.',
      categoryId: 'cat_18',
      price: 899,
      originalPrice: 1199,
      discount: 25,
      duration: '35 mins',
      rating: 4.7,
      reviewCount: 1987,
      included: ['Warm medicated oil', 'Spinal pad placement', 'Oil retention therapy', 'Light massage'],
      bookingCount: 9000,
      image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=400',
    ),
    // --- srv_19: Kati Basti (cat_19) ---
    ServiceModel(
      id: 'srv_19',
      name: 'Kati Basti (Lower Back Oil Pooling)',
      description: 'Warm medicated oil retained over the lower back region using dough dam. Best for lumbar pain and sciatica.',
      categoryId: 'cat_19',
      price: 1199,
      originalPrice: 1599,
      discount: 25,
      duration: '40 mins',
      rating: 4.8,
      reviewCount: 6543,
      included: ['Dough dam preparation', 'Warm medicated oil', 'Oil retention therapy', 'Gentle massage'],
      isBestSeller: true,
      bookingCount: 38000,
      image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=400',
    ),
    // --- srv_20: Greeva Basti (cat_20) ---
    ServiceModel(
      id: 'srv_20',
      name: 'Greeva Basti (Neck Oil Pooling)',
      description: 'Oil retention therapy over the cervical region for neck pain, cervical spondylosis and stiffness.',
      categoryId: 'cat_20',
      price: 1199,
      originalPrice: 1599,
      discount: 25,
      duration: '40 mins',
      rating: 4.7,
      reviewCount: 4567,
      included: ['Dough dam preparation', 'Warm medicated oil', 'Oil retention', 'Neck massage'],
      bookingCount: 28000,
      image: 'https://images.unsplash.com/photo-1591343395082-e120087004b4?w=400',
    ),
    // --- srv_21: Spinal Basti (cat_21) ---
    ServiceModel(
      id: 'srv_21',
      name: 'Spinal Basti (Spine Oil Pooling)',
      description: 'Oil retention along the entire spinal column using dough dam. For disc prolapse, spondylosis and nerve compression.',
      categoryId: 'cat_21',
      price: 1399,
      originalPrice: 1899,
      discount: 26,
      duration: '45 mins',
      rating: 4.8,
      reviewCount: 2345,
      included: ['Dough dam along spine', 'Warm medicated oil', 'Spinal oil retention', 'Post-therapy massage'],
      bookingCount: 12000,
      image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=400',
    ),
    // --- srv_22: Janu Basti (cat_22) ---
    ServiceModel(
      id: 'srv_22',
      name: 'Janu Basti (Knee Oil Pooling)',
      description: 'Warm oil retention over the knee joint. Highly effective for knee pain, osteoarthritis and joint degeneration.',
      categoryId: 'cat_22',
      price: 1099,
      originalPrice: 1499,
      discount: 26,
      duration: '35 mins',
      rating: 4.7,
      reviewCount: 5432,
      included: ['Dough dam', 'Warm medicated oil', 'Knee joint therapy', 'Light massage'],
      bookingCount: 32000,
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    ),
    // --- srv_23: Hridaya Basti (cat_23) ---
    ServiceModel(
      id: 'srv_23',
      name: 'Hridaya Basti (Heart Oil Pooling)',
      description: 'Oil retention therapy over the heart region for emotional balance, cardiac health and stress relief.',
      categoryId: 'cat_23',
      price: 1399,
      originalPrice: 1899,
      discount: 26,
      duration: '45 mins',
      rating: 4.8,
      reviewCount: 2345,
      included: ['Dough dam', 'Medicated oil for heart', 'Oil retention', 'Chest massage'],
      bookingCount: 12000,
      image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400',
    ),
    // --- srv_24: Nabhi Basti (cat_24) ---
    ServiceModel(
      id: 'srv_24',
      name: 'Nabhi Basti (Navel Oil Pooling)',
      description: 'Oil retention over the navel region for digestive disorders, abdominal pain and energy balance.',
      categoryId: 'cat_24',
      price: 999,
      originalPrice: 1299,
      discount: 23,
      duration: '30 mins',
      rating: 4.6,
      reviewCount: 3210,
      included: ['Dough dam', 'Warm medicated oil', 'Navel therapy', 'Abdominal massage'],
      bookingCount: 15000,
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    ),
    // --- srv_25: Akshi Tarpana (cat_25) ---
    ServiceModel(
      id: 'srv_25',
      name: 'Akshi Tarpana (Eye Rejuvenation)',
      description: 'Medicated ghee retained over the eyes for vision improvement, eye strain and dryness.',
      categoryId: 'cat_25',
      price: 999,
      originalPrice: 1399,
      discount: 28,
      duration: '30 mins',
      rating: 4.8,
      reviewCount: 4321,
      included: ['Dough dam around eyes', 'Medicated ghee', 'Eye rejuvenation', 'Eye exercises'],
      bookingCount: 20000,
      image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400',
    ),
    // --- srv_26: Shiro Basti (cat_26) ---
    ServiceModel(
      id: 'srv_26',
      name: 'Shiro Basti (Head Oil Pooling)',
      description: 'Warm medicated oil retained on the head using a leather cap for severe headaches, facial paralysis and neurological disorders.',
      categoryId: 'cat_26',
      price: 1499,
      originalPrice: 1999,
      discount: 25,
      duration: '45 mins',
      rating: 4.8,
      reviewCount: 1876,
      included: ['Leather cap fitting', 'Warm medicated oil', 'Oil retention on head', 'Post-therapy massage'],
      bookingCount: 8500,
      image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400',
    ),
    // --- srv_27: Vamana Karma (cat_27) ---
    ServiceModel(
      id: 'srv_27',
      name: 'Vamana Karma (Therapeutic Emesis)',
      description: 'Medically supervised therapeutic emesis for deep cleansing of Kapha dosha. Includes pre & post care.',
      categoryId: 'cat_27',
      price: 2999,
      originalPrice: 3999,
      discount: 25,
      duration: '90 mins',
      rating: 4.9,
      reviewCount: 2345,
      included: ['Pre-therapy preparation', 'Medicated emetic', 'Supervised procedure', 'Post-therapy diet plan'],
      isBestSeller: true,
      bookingCount: 8000,
      warranty: 'Doctor supervised',
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400',
    ),
    // --- srv_28: Virechana Karma (cat_28) ---
    ServiceModel(
      id: 'srv_28',
      name: 'Virechana Karma (Therapeutic Purgation)',
      description: 'Therapeutic purgation for Pitta dosha cleansing. Effective for skin disorders, liver detox and digestion.',
      categoryId: 'cat_28',
      price: 2499,
      originalPrice: 3499,
      discount: 28,
      duration: '60 mins',
      rating: 4.8,
      reviewCount: 3210,
      included: ['Snehapana preparation', 'Medicated purgative', 'Supervised therapy', 'Samsarjana Krama diet'],
      bookingCount: 10000,
      warranty: 'Doctor supervised',
      image: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=400',
    ),
    // --- srv_29: Basti Karma (cat_29) ---
    ServiceModel(
      id: 'srv_29',
      name: 'Basti Karma (Therapeutic Enema)',
      description: 'Medicated enema therapy for Vata disorders, constipation, neurological conditions and joint diseases.',
      categoryId: 'cat_29',
      price: 1999,
      originalPrice: 2799,
      discount: 28,
      duration: '60 mins',
      rating: 4.8,
      reviewCount: 2876,
      included: ['Medicated decoction preparation', 'Supervised administration', 'Rest period', 'Diet guidance'],
      isBestSeller: true,
      bookingCount: 14000,
      warranty: 'Doctor supervised',
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400',
    ),
    // --- srv_30: Nasya Karma (cat_30) ---
    ServiceModel(
      id: 'srv_30',
      name: 'Nasya Karma (Nasal Therapy)',
      description: 'Medicated oil or herbal preparation instilled through nose for sinus, migraine and mental clarity.',
      categoryId: 'cat_30',
      price: 899,
      originalPrice: 1199,
      discount: 25,
      duration: '25 mins',
      rating: 4.7,
      reviewCount: 5678,
      included: ['Facial steam', 'Medicated oil/drops', 'Nasal instillation', 'Face massage'],
      isBestSeller: true,
      bookingCount: 30000,
      image: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=400',
    ),
    // --- srv_31: Marma Chikitsa (cat_31) ---
    ServiceModel(
      id: 'srv_31',
      name: 'Marma Chikitsa (Marma Therapy)',
      description: 'Ancient pressure point therapy targeting 107 vital marma points for energy flow and healing.',
      categoryId: 'cat_31',
      price: 1799,
      originalPrice: 2299,
      discount: 21,
      duration: '60 mins',
      rating: 4.9,
      reviewCount: 4567,
      included: ['Marma point assessment', 'Medicated oil', 'Pressure point therapy', 'Energy balancing'],
      isBestSeller: true,
      bookingCount: 25000,
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
    ),
    // --- srv_32: Dry Cupping Therapy (cat_32) ---
    ServiceModel(
      id: 'srv_32',
      name: 'Dry Cupping Therapy (Alabu)',
      description: 'Traditional cupping using cups to create suction for muscle relaxation, pain relief and detoxification.',
      categoryId: 'cat_32',
      price: 899,
      originalPrice: 1199,
      discount: 25,
      duration: '30 mins',
      rating: 4.6,
      reviewCount: 3456,
      included: ['Skin preparation', 'Cupping therapy', 'Targeted application', 'Post-therapy care'],
      bookingCount: 18000,
      image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=400',
    ),
    // --- srv_33: Wet Cupping Therapy (cat_33) ---
    ServiceModel(
      id: 'srv_33',
      name: 'Wet Cupping Therapy (Hijama)',
      description: 'Controlled wet cupping with minor skin puncture for blood purification, chronic pain and toxin removal.',
      categoryId: 'cat_33',
      price: 1199,
      originalPrice: 1599,
      discount: 25,
      duration: '40 mins',
      rating: 4.7,
      reviewCount: 1987,
      included: ['Sterile preparation', 'Controlled cupping', 'Blood purification', 'Wound care & dressing'],
      bookingCount: 9000,
      warranty: 'Doctor supervised',
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    ),
    // --- srv_34: Raktamokshana (cat_34) ---
    ServiceModel(
      id: 'srv_34',
      name: 'Raktamokshana (Leech Therapy)',
      description: 'Medicinal leech therapy for blood purification, skin diseases and localized blood disorders.',
      categoryId: 'cat_34',
      price: 1499,
      originalPrice: 1999,
      discount: 25,
      duration: '45 mins',
      rating: 4.7,
      reviewCount: 1987,
      included: ['Medical assessment', 'Sterile leeches', 'Supervised therapy', 'Wound care'],
      bookingCount: 8000,
      warranty: 'Doctor supervised',
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400',
    ),
    // --- srv_35: Sira Bhedana (cat_35) ---
    ServiceModel(
      id: 'srv_35',
      name: 'Sira Bhedana (Venepuncture Therapy)',
      description: 'Ancient Ayurvedic bloodletting from specific veins for deep-seated Pitta and blood disorders.',
      categoryId: 'cat_35',
      price: 1699,
      originalPrice: 2299,
      discount: 26,
      duration: '45 mins',
      rating: 4.7,
      reviewCount: 1234,
      included: ['Medical assessment', 'Sterile procedure', 'Controlled venepuncture', 'Post-therapy care'],
      bookingCount: 5000,
      warranty: 'Doctor supervised',
      image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=400',
    ),
    // --- srv_36: Fire Cupping Therapy (cat_36) ---
    ServiceModel(
      id: 'srv_36',
      name: 'Fire Cupping Therapy',
      description: 'Traditional fire cupping using heat to create vacuum for deep muscle tension, stagnation and chronic pain.',
      categoryId: 'cat_36',
      price: 999,
      originalPrice: 1399,
      discount: 28,
      duration: '35 mins',
      rating: 4.6,
      reviewCount: 2134,
      included: ['Skin preparation', 'Fire cupping technique', 'Targeted placement', 'Post-therapy oil application'],
      bookingCount: 10000,
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    ),
    // --- srv_37: Vidalaka (cat_37) ---
    ServiceModel(
      id: 'srv_37',
      name: 'Vidalaka (Face Pack Therapy)',
      description: 'Ayurvedic herbal face pack therapy for skin rejuvenation, pigmentation and natural glow.',
      categoryId: 'cat_37',
      price: 799,
      originalPrice: 999,
      discount: 20,
      duration: '35 mins',
      rating: 4.7,
      reviewCount: 4321,
      included: ['Herbal paste preparation', 'Face application', 'Cooling therapy', 'Gentle wash'],
      bookingCount: 22000,
      image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400',
    ),
    // --- srv_38: Janu Dhara (cat_38) ---
    ServiceModel(
      id: 'srv_38',
      name: 'Janu Dhara (Knee Oil Pouring)',
      description: 'Continuous pouring of warm medicated oil over the knee joint for chronic knee pain and arthritis.',
      categoryId: 'cat_38',
      price: 1099,
      originalPrice: 1499,
      discount: 26,
      duration: '35 mins',
      rating: 4.7,
      reviewCount: 2345,
      included: ['Warm medicated oil', 'Continuous knee pouring', 'Joint massage', 'Rest period'],
      bookingCount: 13000,
      image: 'https://images.unsplash.com/photo-1591343395082-e120087004b4?w=400',
    ),
    // --- srv_39: Kati Dhara (cat_39) ---
    ServiceModel(
      id: 'srv_39',
      name: 'Kati Dhara (Lower Back Oil Pouring)',
      description: 'Continuous warm oil pouring over the lower back for lumbar spondylosis, disc issues and chronic pain.',
      categoryId: 'cat_39',
      price: 1099,
      originalPrice: 1499,
      discount: 26,
      duration: '35 mins',
      rating: 4.7,
      reviewCount: 2567,
      included: ['Warm medicated oil', 'Continuous lower back pouring', 'Back massage', 'Rest period'],
      bookingCount: 14000,
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=400',
    ),
    // --- srv_40: Manya Dhara / Greeva Dhara (cat_40) ---
    ServiceModel(
      id: 'srv_40',
      name: 'Manya Dhara / Greeva Dhara (Neck Oil Pouring)',
      description: 'Continuous oil pouring over the neck and cervical region for neck stiffness, spondylosis and frozen shoulder.',
      categoryId: 'cat_40',
      price: 1099,
      originalPrice: 1499,
      discount: 26,
      duration: '35 mins',
      rating: 4.6,
      reviewCount: 1876,
      included: ['Warm medicated oil', 'Continuous neck pouring', 'Shoulder massage', 'Rest period'],
      bookingCount: 10000,
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    ),
    // --- srv_41: Prastara Dhara / Spinal Dhara (cat_41) ---
    ServiceModel(
      id: 'srv_41',
      name: 'Prastara Dhara (Spinal Oil Pouring)',
      description: 'Continuous warm oil pouring along the entire spine for spinal disorders, nerve weakness and Vata imbalance.',
      categoryId: 'cat_41',
      price: 1299,
      originalPrice: 1799,
      discount: 27,
      duration: '40 mins',
      rating: 4.7,
      reviewCount: 1654,
      included: ['Warm medicated oil', 'Full spinal oil pouring', 'Spine massage', 'Relaxation period'],
      bookingCount: 8000,
      image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=400',
    ),
    // --- srv_42: Hridaya Dhara (cat_42) ---
    ServiceModel(
      id: 'srv_42',
      name: 'Hridaya Dhara (Heart Oil Pouring)',
      description: 'Continuous warm oil pouring over the heart region for emotional healing, anxiety and cardiac wellness.',
      categoryId: 'cat_42',
      price: 1299,
      originalPrice: 1799,
      discount: 27,
      duration: '40 mins',
      rating: 4.7,
      reviewCount: 1432,
      included: ['Warm medicated oil', 'Heart area oil pouring', 'Chest massage', 'Rest and relaxation'],
      bookingCount: 7000,
      image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400',
    ),
    // --- srv_43: Niruha Basti (cat_43) ---
    ServiceModel(
      id: 'srv_43',
      name: 'Niruha Basti (Decoction Enema)',
      description: 'Herbal decoction-based enema for deep Vata cleansing, neurological disorders and chronic constipation.',
      categoryId: 'cat_43',
      price: 1799,
      originalPrice: 2499,
      discount: 28,
      duration: '60 mins',
      rating: 4.8,
      reviewCount: 1987,
      included: ['Herbal decoction preparation', 'Supervised administration', 'Rest period', 'Diet plan'],
      bookingCount: 9000,
      warranty: 'Doctor supervised',
      image: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=400',
    ),
    // --- srv_44: Medicinal Oil Basti (cat_44) ---
    ServiceModel(
      id: 'srv_44',
      name: 'Medicinal Oil Basti (Anuvasana Basti)',
      description: 'Oil-based enema using medicated oils for nourishing tissues, joint lubrication and Vata balance.',
      categoryId: 'cat_44',
      price: 1599,
      originalPrice: 2199,
      discount: 27,
      duration: '45 mins',
      rating: 4.7,
      reviewCount: 1765,
      included: ['Medicated oil preparation', 'Supervised oil enema', 'Rest period', 'Post-therapy diet'],
      bookingCount: 8000,
      warranty: 'Doctor supervised',
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=400',
    ),
    // --- srv_45: Karna Purana (cat_45) ---
    ServiceModel(
      id: 'srv_45',
      name: 'Karna Purana (Ear Oil Filling)',
      description: 'Warm medicated oil instilled in the ears for ear health, tinnitus and jaw disorders.',
      categoryId: 'cat_45',
      price: 799,
      originalPrice: 999,
      discount: 20,
      duration: '20 mins',
      rating: 4.6,
      reviewCount: 2876,
      included: ['Warm medicated oil', 'Ear canal filling', 'Face massage', 'Rest period'],
      bookingCount: 12000,
      image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400',
    ),
    // --- srv_46: Dry Needling Therapy (cat_46) ---
    ServiceModel(
      id: 'srv_46',
      name: 'Dry Needling Therapy',
      description: 'Thin needle insertion into myofascial trigger points for chronic muscle pain, tension and rehabilitation.',
      categoryId: 'cat_46',
      price: 999,
      originalPrice: 1399,
      discount: 28,
      duration: '30 mins',
      rating: 4.7,
      reviewCount: 2134,
      included: ['Trigger point assessment', 'Sterile needles', 'Targeted insertion', 'Post-therapy stretching'],
      bookingCount: 11000,
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    ),
    // --- srv_47: Agni Karma (cat_47) ---
    ServiceModel(
      id: 'srv_47',
      name: 'Agni Karma (Thermal Cauterization)',
      description: 'Ancient Ayurvedic thermal therapy for chronic pain, musculoskeletal disorders and nerve conditions.',
      categoryId: 'cat_47',
      price: 1299,
      originalPrice: 1699,
      discount: 23,
      duration: '30 mins',
      rating: 4.8,
      reviewCount: 2345,
      included: ['Medical assessment', 'Localized thermal therapy', 'Post-therapy care', 'Follow-up guidance'],
      isBestSeller: true,
      bookingCount: 15000,
      warranty: 'Doctor supervised',
      image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400',
    ),
    // --- srv_48: Agni Karma by Needle (cat_48) ---
    ServiceModel(
      id: 'srv_48',
      name: 'Agni Karma by Needle (Suchi Dagdha)',
      description: 'Precision thermal therapy using heated needles for small joint pain, tendon issues and neuralgic pain.',
      categoryId: 'cat_48',
      price: 1199,
      originalPrice: 1599,
      discount: 25,
      duration: '25 mins',
      rating: 4.7,
      reviewCount: 1543,
      included: ['Medical assessment', 'Heated needle therapy', 'Targeted application', 'Post-therapy dressing'],
      bookingCount: 7000,
      warranty: 'Doctor supervised',
      image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    ),
    // --- srv_49: Agni Patra Swedana (cat_49) ---
    ServiceModel(
      id: 'srv_49',
      name: 'Agni Patra Swedana (Heated Leaf Fomentation)',
      description: 'Fomentation using heated herbal leaves for localized pain, muscle spasm and joint inflammation.',
      categoryId: 'cat_49',
      price: 1099,
      originalPrice: 1499,
      discount: 26,
      duration: '35 mins',
      rating: 4.6,
      reviewCount: 1234,
      included: ['Herbal leaf preparation', 'Heated fomentation', 'Targeted application', 'Oil massage'],
      bookingCount: 6500,
      image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400',
    ),
    // --- srv_50: Electric Pen Therapy (cat_50) ---
    ServiceModel(
      id: 'srv_50',
      name: 'Electric Pen Therapy (E-Stimulation)',
      description: 'Modern electro-stimulation therapy combined with Ayurvedic points for nerve pain, paralysis and rehabilitation.',
      categoryId: 'cat_50',
      price: 899,
      originalPrice: 1299,
      discount: 30,
      duration: '25 mins',
      rating: 4.6,
      reviewCount: 1876,
      included: ['Point assessment', 'Electric pen stimulation', 'Targeted nerve therapy', 'Post-therapy rest'],
      bookingCount: 9500,
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    ),
  ];

  // ==================== PROVIDERS ====================
  static final List<ProviderModel> providers = [
    ProviderModel(
      id: 'prov_1',
      name: 'Dr. Radhika Sharma',
      rating: 4.9,
      reviewCount: 856,
      experience: 8,
      servicesCompleted: 2450,
      isVerified: true,
      skills: ['Panchakarma', 'Vamana', 'Virechana', 'Nasya'],
      bio: 'BAMS, MD Ayurveda. Panchakarma specialist with 8 years of clinical experience.',
      profileImage: 'https://randomuser.me/api/portraits/women/44.jpg',
    ),
    ProviderModel(
      id: 'prov_2',
      name: 'Vaidya Suresh Patil',
      rating: 4.8,
      reviewCount: 1234,
      experience: 12,
      servicesCompleted: 3800,
      isVerified: true,
      skills: ['Abhyanga', 'Shirodhara', 'Swedana', 'Dhara'],
      bio: 'Certified Ayurvedic therapist specializing in Abhyanga and oil-based therapies.',
      profileImage: 'https://randomuser.me/api/portraits/men/32.jpg',
    ),
    ProviderModel(
      id: 'prov_3',
      name: 'Dr. Anand Kulkarni',
      rating: 4.9,
      reviewCount: 678,
      experience: 15,
      servicesCompleted: 4200,
      isVerified: true,
      skills: ['Marma Chikitsa', 'Basti', 'Agni Karma', 'Cupping'],
      bio: 'Senior Ayurvedic physician with 15 years in Marma therapy and Basti treatments.',
      profileImage: 'https://randomuser.me/api/portraits/men/75.jpg',
    ),
    ProviderModel(
      id: 'prov_4',
      name: 'Dr. Priya Nair',
      rating: 4.7,
      reviewCount: 543,
      experience: 6,
      servicesCompleted: 1890,
      isVerified: true,
      skills: ['Shirodhara', 'Takradhara', 'Pichu', 'Dhara'],
      bio: 'BAMS graduate specializing in Dhara and Pichu therapies for stress management.',
      profileImage: 'https://randomuser.me/api/portraits/women/68.jpg',
    ),
    ProviderModel(
      id: 'prov_5',
      name: 'Vaidya Ramesh Joshi',
      rating: 4.8,
      reviewCount: 987,
      experience: 10,
      servicesCompleted: 2900,
      isVerified: true,
      skills: ['Cupping', 'Agni Karma', 'Raktamokshana', 'Dry Needling'],
      bio: 'Expert in traditional Ayurvedic surgical procedures and therapeutic interventions.',
      profileImage: 'https://randomuser.me/api/portraits/men/45.jpg',
    ),
    ProviderModel(
      id: 'prov_6',
      name: 'Dr. Meera Iyer',
      rating: 4.8,
      reviewCount: 432,
      experience: 7,
      servicesCompleted: 1200,
      isVerified: true,
      skills: ['Swedana', 'Pottali', 'Vidalaka', 'Detox'],
      bio: 'Ayurvedic wellness expert specializing in detoxification and herbal therapies.',
      profileImage: 'https://randomuser.me/api/portraits/women/55.jpg',
    ),
  ];

  // ==================== REVIEWS ====================
  static final List<ReviewModel> reviews = [
    ReviewModel(
      id: 'rev_1',
      userName: 'Neha Gupta',
      rating: 5.0,
      comment: 'The Full Body Abhyanga was incredible! I felt completely relaxed and my body pain reduced significantly.',
      date: DateTime.now().subtract(const Duration(days: 2)),
      serviceId: 'srv_1',
      userImage: 'https://randomuser.me/api/portraits/women/22.jpg',
    ),
    ReviewModel(
      id: 'rev_2',
      userName: 'Amit Patel',
      rating: 4.5,
      comment: 'Shirodhara was a life-changing experience. My insomnia has improved significantly after 3 sessions.',
      date: DateTime.now().subtract(const Duration(days: 5)),
      serviceId: 'srv_10',
      userImage: 'https://randomuser.me/api/portraits/men/28.jpg',
    ),
    ReviewModel(
      id: 'rev_3',
      userName: 'Ritu Singh',
      rating: 5.0,
      comment: 'Vamana Karma under Dr. Radhika was very well supervised. My chronic skin issues are resolving beautifully.',
      date: DateTime.now().subtract(const Duration(days: 1)),
      serviceId: 'srv_27',
      userImage: 'https://randomuser.me/api/portraits/women/33.jpg',
    ),
    ReviewModel(
      id: 'rev_4',
      userName: 'Sanjay Mehta',
      rating: 4.0,
      comment: 'Kati Basti provided great relief for my lower back pain. The therapist was very skilled and gentle.',
      date: DateTime.now().subtract(const Duration(days: 7)),
      serviceId: 'srv_19',
      userImage: 'https://randomuser.me/api/portraits/men/55.jpg',
    ),
    ReviewModel(
      id: 'rev_5',
      userName: 'Kavitha R',
      rating: 5.0,
      comment: 'Marma Chikitsa by Dr. Anand is phenomenal. My energy levels and pain management improved drastically.',
      date: DateTime.now().subtract(const Duration(days: 3)),
      serviceId: 'srv_31',
      userImage: 'https://randomuser.me/api/portraits/women/45.jpg',
    ),
    ReviewModel(
      id: 'rev_6',
      userName: 'Deepak Kumar',
      rating: 4.5,
      comment: 'Agni Karma therapy gave me relief from chronic shoulder pain that nothing else could fix. Highly recommended!',
      date: DateTime.now().subtract(const Duration(days: 4)),
      serviceId: 'srv_47',
      userImage: 'https://randomuser.me/api/portraits/men/62.jpg',
    ),
  ];

  // ==================== BANNERS ====================
  static final List<BannerModel> banners = [
    BannerModel(
      id: 'ban_1',
      title: 'Panchakarma Special',
      subtitle: 'Up to 40% off on all Panchakarma therapies',
      discount: '40%',
      backgroundColor: const Color(0xFFB71C1C),
      image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600',
    ),
    BannerModel(
      id: 'ban_2',
      title: 'Abhyanga & Massage',
      subtitle: 'Full Body Abhyanga starting at just \u20b91,499',
      discount: '30%',
      backgroundColor: const Color(0xFFE65100),
      image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600',
    ),
    BannerModel(
      id: 'ban_3',
      title: 'Basti Therapies',
      subtitle: 'Targeted oil pooling for joint & back pain relief',
      discount: '25%',
      backgroundColor: const Color(0xFF0D47A1),
      image: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=600',
    ),
    BannerModel(
      id: 'ban_4',
      title: 'Wellness Membership',
      subtitle: 'Get 5-15% off on every therapy booking!',
      discount: '15%',
      backgroundColor: const Color(0xFF6C63FF),
      actionText: 'Join Now',
    ),
    BannerModel(
      id: 'ban_5',
      title: 'Shirodhara Experience',
      subtitle: 'Relax your mind with premium Shirodhara therapy',
      discount: '35%',
      backgroundColor: const Color(0xFF1565C0),
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=600',
    ),
  ];

  // ==================== BOOKINGS ====================
  static final List<BookingModel> bookings = [
    BookingModel(
      id: 'BK-2024001',
      serviceName: 'Shirodhara',
      categoryName: 'Shirodhara',
      providerName: 'Dr. Priya Nair',
      providerRating: 4.7,
      bookingDate: DateTime.now().add(const Duration(days: 2)),
      timeSlot: '10:00 AM - 11:00 AM',
      address: '123, Green Park, New Delhi - 110016',
      totalAmount: 1299,
      status: BookingStatus.upcoming,
      items: [BookingItem(name: 'Shirodhara Session', price: 1299)],
      paymentMethod: 'UPI',
      serviceImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbec6d?w=400',
      providerImage: 'https://randomuser.me/api/portraits/women/68.jpg',
    ),
    BookingModel(
      id: 'BK-2024002',
      serviceName: 'Full Body Abhyanga',
      categoryName: 'Full Body Abhyanga',
      providerName: 'Vaidya Suresh Patil',
      providerRating: 4.8,
      bookingDate: DateTime.now().subtract(const Duration(days: 3)),
      timeSlot: '9:00 AM - 10:00 AM',
      address: '456, Sector 22, Noida - 201301',
      totalAmount: 1499,
      discount: 500,
      status: BookingStatus.completed,
      items: [BookingItem(name: 'Full Body Abhyanga (60 mins)', price: 1499)],
      paymentMethod: 'Card',
      isRated: true,
      serviceImage: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400',
      providerImage: 'https://randomuser.me/api/portraits/men/32.jpg',
    ),
    BookingModel(
      id: 'BK-2024003',
      serviceName: 'Kati Basti + Nasya Karma',
      categoryName: 'Basti Therapies',
      providerName: 'Dr. Anand Kulkarni',
      providerRating: 4.9,
      bookingDate: DateTime.now().subtract(const Duration(days: 7)),
      timeSlot: '2:00 PM - 3:30 PM',
      address: '789, MG Road, Bangalore - 560001',
      totalAmount: 2098,
      status: BookingStatus.completed,
      items: [
        BookingItem(name: 'Kati Basti', price: 1199),
        BookingItem(name: 'Nasya Karma', price: 899),
      ],
      paymentMethod: 'Wallet',
      serviceImage: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=400',
      providerImage: 'https://randomuser.me/api/portraits/men/75.jpg',
    ),
  ];

  // ==================== USER ====================
  static final UserModel currentUser = UserModel(
    id: 'user_1',
    name: 'Arun Kumar',
    email: 'arun.kumar@email.com',
    phone: '+91 98765 43210',
    profileImage: 'https://randomuser.me/api/portraits/men/85.jpg',
    walletBalance: 1250,
    isUcPlusMember: false,
    referralCode: 'ARUN250',
    addresses: [
      AddressModel(
        id: 'addr_1',
        label: 'Home',
        fullAddress: '123, Green Park Main, Block A',
        landmark: 'Near Green Park Metro Station',
        city: 'New Delhi',
        pincode: '110016',
        isDefault: true,
      ),
      AddressModel(
        id: 'addr_2',
        label: 'Office',
        fullAddress: '456, Cyber City, DLF Phase 2',
        landmark: 'Near Rapid Metro Station',
        city: 'Gurugram',
        pincode: '122002',
      ),
    ],
  );

  // ==================== OFFERS / COUPONS ====================
  static final List<Map<String, dynamic>> coupons = [
    {
      'code': 'FIRST50',
      'title': '50% OFF on first therapy',
      'description': 'Get 50% off up to \u20b9500 on your first Ayurvedic therapy booking',
      'discount': 50,
      'maxDiscount': 500,
      'minOrder': 499,
      'validTill': '31 Mar 2026',
    },
    {
      'code': 'PANCHA30',
      'title': '30% OFF on Panchakarma',
      'description': 'Save 30% on all Panchakarma therapies including Vamana & Virechana',
      'discount': 30,
      'maxDiscount': 1000,
      'minOrder': 1999,
      'validTill': '30 Jun 2026',
    },
    {
      'code': 'BASTI20',
      'title': '20% OFF on Basti Therapies',
      'description': 'Save 20% on Kati, Greeva, Janu & all Basti treatments',
      'discount': 20,
      'maxDiscount': 400,
      'minOrder': 999,
      'validTill': '28 Feb 2026',
    },
    {
      'code': 'ABHYANGA40',
      'title': '40% OFF on Abhyanga',
      'description': 'Pamper yourself with 40% off on all Abhyanga massage therapies',
      'discount': 40,
      'maxDiscount': 600,
      'minOrder': 699,
      'validTill': '15 Apr 2026',
    },
  ];

  // ==================== FAQ ====================
  static final List<Map<String, String>> faqs = [
    {
      'question': 'What is Panchakarma therapy?',
      'answer': 'Panchakarma is a five-fold Ayurvedic detoxification therapy consisting of Vamana (emesis), Virechana (purgation), Basti (enema), Nasya (nasal therapy) and Raktamokshana (bloodletting). It deeply cleanses the body and restores balance.',
    },
    {
      'question': 'Are the therapists qualified and certified?',
      'answer': 'Yes, all our therapists are BAMS qualified or certified Ayurvedic practitioners with extensive training. Panchakarma procedures are always supervised by experienced Ayurvedic physicians.',
    },
    {
      'question': 'Are there any side effects of Ayurvedic therapies?',
      'answer': 'Ayurvedic therapies are generally safe when performed by qualified practitioners. Mild reactions like fatigue or detox symptoms may occur temporarily. All therapies include pre-assessment to ensure suitability.',
    },
    {
      'question': 'How should I prepare before a therapy session?',
      'answer': 'Eat a light meal 2 hours before your session. Wear comfortable clothing. Inform your therapist about any medical conditions or allergies. For Panchakarma, follow the prescribed preparatory diet.',
    },
    {
      'question': 'Can I combine multiple therapies in one session?',
      'answer': 'Yes, certain therapies complement each other well. For example, Abhyanga followed by Swedana, or Nasya with Shirodhara. Our practitioners will recommend the best combination based on your health needs.',
    },
  ];

  // ==================== TIME SLOTS ====================
  static final List<String> timeSlots = [
    '8:00 AM',
    '9:00 AM',
    '10:00 AM',
    '11:00 AM',
    '12:00 PM',
    '1:00 PM',
    '2:00 PM',
    '3:00 PM',
    '4:00 PM',
    '5:00 PM',
    '6:00 PM',
    '7:00 PM',
  ];
}
